version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - ${DB_PATH}:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ${MOSQUITTO_PATH}/config:/mosquitto/config
      - ${MOSQUITTO_PATH}/data:/mosquitto/data
      - ${MOSQUITTO_PATH}/log:/mosquitto/log
    ports:
      - 1883:1883
    restart: unless-stopped
